name: hucel_core
description: This My Best Core Components and Uniq Code variants And Usefull Widgets
version: 0.2.0

homepage: https://github.com/HalilUcel14/hucel_core_packages.git

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ## - language management - ##
  easy_localization: ^3.0.1

  ## - web management - ##
  url_launcher: ^6.0.20
  share: ^2.0.4
  
  ## - İnput Formatter - ##
  mask_text_input_formatter: ^2.3.0
  
  ## - State Management - ##
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1
  mobx_codegen: ^2.0.5+2
  provider: ^6.0.2

  ## - File Management - ##
  path_provider: ^2.0.9
  mime: ^1.0.1

  ## - Data Management - ##
  shared_preferences: ^2.0.13
 
  ## - Device Management - ##
  device_info: ^2.0.0
  package_info_plus: ^1.4.2

  ## - Firebase Management - ##
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.2.12
  
  # -- social account -- #
  google_sign_in: ^5.3.0
  flutter_facebook_auth: ^4.2.1
  twitter_login: ^4.2.2

  ## - Other Packages - ##
  logger: ^1.1.0
  connectivity_plus: ^2.3.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  ## - State Management - ##
  build_runner: ^2.1.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
