// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XJjbHvkCUM5g9ydWQYsFiHLg0rqQbas',
    appId: '1:794573244493:web:eb67beb6dc659ebe22f404',
    messagingSenderId: '794573244493',
    projectId: 'codeofland-web',
    authDomain: 'codeofland-web.firebaseapp.com',
    storageBucket: 'codeofland-web.appspot.com',
    measurementId: 'G-7DQNZ2S05M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU98Y8HCEqs5VMGDiF6YXRLOX7XDfo4Pw',
    appId: '1:794573244493:android:ec35227ddcf303f422f404',
    messagingSenderId: '794573244493',
    projectId: 'codeofland-web',
    storageBucket: 'codeofland-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq82sBmxtdPbLCUVHYOD5jRJqr_5AdzEc',
    appId: '1:794573244493:ios:d356f3ae5ba9bb9322f404',
    messagingSenderId: '794573244493',
    projectId: 'codeofland-web',
    storageBucket: 'codeofland-web.appspot.com',
    iosClientId:
        '794573244493-ftf0n0g984hsk50tdvd01mlng8rame5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeoflandWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq82sBmxtdPbLCUVHYOD5jRJqr_5AdzEc',
    appId: '1:794573244493:ios:d356f3ae5ba9bb9322f404',
    messagingSenderId: '794573244493',
    projectId: 'codeofland-web',
    storageBucket: 'codeofland-web.appspot.com',
    iosClientId:
        '794573244493-ftf0n0g984hsk50tdvd01mlng8rame5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeoflandWebsite',
  );
}
